name:                jamgamename
version:             0.1.0.0
github:              "githubuser/jamgamename"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/jamgamename#readme>

dependencies:
- base >= 4.11 && < 5
- gloss ^>=1.13.0.1
- gloss-game >=0.3.3.0
- gloss-export >=0.1.0.0
- JuicyPixels >=3.3.8
- apecs ^>=0.9.4
- apecs-physics <=0.4.4
- apecs-gloss ^>=0.2.4
- random
- linear
- containers >= 0.6.4.1
- unordered-containers >=0.2.17.0
- vector >=0.12.3.1
- astar >=0.3.0.0
- debug-time >=0.1.0.1
- proteaaudio >=0.9.2
- filepath >=1.4.2.1
- bytestring >=0.10.12.1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  jamgamename-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jamgamename

tests:
  jamgamename-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jamgamename
